### ISSUE TITLE
Why does this require older firmware?

### ISSUE THREAD

**Issue by maddox** [No0ne/DI.FM-Tesla#1]
Is there an explanation on why it requires older firmware, which clearly no one has on their car. 

So is this trick, and the project, dead?

**Comment by No0ne** [comment]
I'm sorry but the script is currently not working as they "improved" the TuneIn player in 2020.24.6 and higher, see https://www.notateslaapp.com/software-updates/version/2020.24.6/release-notes

The player used to talk http directly to TuneIn servers. After this version they switched to using https with Teslas own servers, so no sniffing of the wifi traffic any more. The bigger problem is that any custom URL added in the TuneIn app doesn't show up in the car, might be filtered by the new API or in the car it self (can't tell, its https now).

But it might be possible to do custom streaming URLs again in future versions, see: https://twitter.com/greentheonly/status/1342994224967528449
